

# This file was *autogenerated* from the file Check_Dim_Zero.sage
from sage.all_cmdline import *   # import sage library

_sage_const_1 = Integer(1); _sage_const_2 = Integer(2)
from SiegelModularForms import *
import time

k = ZZ(sys.argv[_sage_const_1 ])
print("\nk = {}\n".format(k))
t = time.time()
test = SMF(_sage_const_2 ,k,False)._ConfirmDimZero()
print("\n")
print(time.time() - t)
print(test)
assert test


